# Generated by Django 4.1.4 on 2022-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('auther', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
