# Generated by Django 4.1.4 on 2022-12-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_tag', models.CharField(max_length=100)),
                ('artist_img', models.FileField(default=None, max_length=250, null=True, upload_to='artist/')),
            ],
        ),
    ]
